### ISSUE TITLE
[BUG] currentGasBlip = CreateBlip(closestCoords, Config.GasStations[closestLocation].label)

### ISSUE THREAD

**Issue by AndreasFromDanmark** [CodineDev/cdn-fuel#25]
Getting this error

![image](https://user-images.githubusercontent.com/35656492/210172779-a60d9e74-e7b6-4b27-86e1-409248dde525.png)

![image](https://user-images.githubusercontent.com/35656492/210172826-b3551c10-302e-48d0-a192-0f31729c9f0f.png)

**Comment by dnelyk** [comment]
Should be fixed:

https://github.com/CodineDev/cdn-fuel/commit/ab01dcb501e8ced6178b1a11473ee75934169379

**Comment by SirOMGitsYOU** [comment]
Definitely not fixed. Just tried this no error message is showing up but only 1 blip is showing for me (Ottos)
